import Head from "next/head";
import Header from "../components/navigation/Header";
import Footer from "../components/navigation/Footer";

// Import Swiper styles
import "swiper/css";

// Tailwind css
import "../styles/globals.css";

// fonts
import "../public/assets/fonts/sui-generis/stylesheet.css";
import "../public/assets/fonts/gilroy/stylesheet.css";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Netops Ninjas</title>
        <link rel="icon" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>
      <div className="bg-primary min-h-screen flex flex-col">
        <Header /> 
        <div className="flex-1">
          <Component {...pageProps} />
        </div>
        <Footer /> 
      </div>
    </>
  );
}
